import requests

# Generate methods.py
fh = open("prayer_times_calculator_offline/methods.py", "w")
fh.write(
    """# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT EDIT
import typing


CALCULATION_METHODS: dict[str, dict[str, typing.Union[float, str]]] = {}
"""
)
methods_response = requests.get("https://api.aladhan.com/v1/methods")
methods_response.raise_for_status()

for key, method in methods_response.json()["data"].items():
    fh.write(
        f'CALCULATION_METHODS[{repr(key.lower())}] = {repr(method.get("params", {}))}\n'
    )
